version: '3.7'

services:

  myneo4j:
    container_name: db
    image: neo4j:4.4.27-enterprise
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - net

  app:
    container_name: app
    image: springboot-neo4j:1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ORG_NEO4J_DRIVER_URI=bolt://myneo4j:7687
    ports:
      - "8080:8080"
    networks:
      - net

networks:
  net: